package com.nao20010128nao.MUT;

public final class Resources {
	public static final String testString = "§l§2Minecraft §3Formatting §6text §bfrom §eWikis §band §1Servers\r\n"
			+ "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n"
			+ "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n"
			+ "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n"
			+ "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n"
			+ "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n"
			+ "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n"
			+ "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n"
			+ "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n"
			+ "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n"
			+ "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n"
			+ "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n"
			+ "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n"
			+ "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n"
			+ "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n"
			+ "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n"
			+ "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n"
			+ "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n" + "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n"
			+ "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n" + "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n"
			+ "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n" + "§r\r\n" + "\r\n"
			+ "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n" + "§4§lMinecraft §6§lServer\r\n"
			+ "\r\n" + "§nMinecraft Formatting\r\n" + "\r\n" + "§r§00 §11 §22 §33\r\n" + "§44 §55 §66 §77\r\n"
			+ "§88 §99 §aa §bb\r\n" + "§cc §dd §ee §ff\r\n" + "\r\n" + "§r§0k §kMinecraft\r\n" + "§rl §lMinecraft\r\n"
			+ "§rm §mMinecraft\r\n" + "§rn §nMinecraft\r\n" + "§ro §oMinecraft\r\n" + "§rr §rMinecraft\r\n" + "\r\n"
			+ "§r\r\n" + "\r\n" + "§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s\r\n" + "\r\n"
			+ "§4§lMinecraft §6§lServer\r\n" + "\r\n" + "\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!\r\n"
			+ "§aHypixel Network §7 §6§l» §c§l1.9 §b§lAND 1.8 §6§l« §e§lCOMPATIBLE!";
	public static final String result = "Minecraft Formatting text from Wikis and Servers\r\n" + "\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n"
			+ "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n"
			+ "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n"
			+ "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n"
			+ "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n"
			+ "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "\r\n" + "Minecraft Formatting\r\n"
			+ "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n"
			+ "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n"
			+ "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n"
			+ "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n"
			+ "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n"
			+ "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n"
			+ "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n"
			+ "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n"
			+ "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "\r\n" + "Minecraft Formatting\r\n"
			+ "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n"
			+ "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n"
			+ "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n"
			+ "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n"
			+ "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n"
			+ "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n"
			+ "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n" + "c d e f\r\n"
			+ "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n" + "o Minecraft\r\n"
			+ "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n"
			+ "\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n" + "8 9 a b\r\n"
			+ "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n" + "n Minecraft\r\n"
			+ "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n" + "Redstone Creations\r\n" + "\r\n"
			+ "Minecraft Server\r\n" + "\r\n" + "Minecraft Formatting\r\n" + "\r\n" + "0 1 2 3\r\n" + "4 5 6 7\r\n"
			+ "8 9 a b\r\n" + "c d e f\r\n" + "\r\n" + "k Minecraft\r\n" + "l Minecraft\r\n" + "m Minecraft\r\n"
			+ "n Minecraft\r\n" + "o Minecraft\r\n" + "r Minecraft\r\n" + "\r\n" + "\r\n" + "\r\n"
			+ "Redstone Creations\r\n" + "\r\n" + "Minecraft Server\r\n" + "\r\n" + "\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n"
			+ "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!\r\n" + "Hypixel Network  » 1.9 AND 1.8 « COMPATIBLE!";
}
